name: Go

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('WORKSPACE', 'BUILD.bazel', 'deps.bzl') }}
          restore-keys: ${{ runner.os }}-bazel-
      - run: bazelisk test //...
